cluster:
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=/dev/null
    --parsable
    --time={resources.runtime}
default-resources:
  - partition=compute
  - mem_mb=2000
  - runtime=90
cluster-status: status-sacct.sh
cluster-cancel: scancel
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
drop-metadata: True
rerun-trigger: mtime
